title: Sad and Angry
description: > # this means to ignore newlines until "baseurl:"
  A journal. For catharsis.
baseurl: "/sad-and-angry"

# Fork into background when serving
detach:  false
markdown: kramdown

destination: "_site/"
layouts_dir: "assets/"
